name: Sync Upstream Tag

on:
  schedule:
    - cron: '0 2 * * *' # Daily at 2 AM UTC
  workflow_dispatch:

jobs:
  sync-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/ome/omero-iviewer.git

      - name: Fetch all tags from upstream
        run: git fetch upstream --tags

      - name: Get latest upstream tag
        id: get_upstream_tag
        run: |
          latest_tag=$(git ls-remote --tags upstream | awk -F/ '{print $3}' | grep -v '{}' | sort -V | tail -n1)
          if [ -z "$latest_tag" ]; then
            echo "No upstream tag found. Exiting."
            exit 0
          fi
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Check if tag exists in fork
        id: check_fork_tag
        run: |
          exists=$(git tag -l "${{ env.LATEST_TAG }}")
          if [ -z "$exists" ]; then
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Debug tag existence
        run: echo "Tag exists: ${{ steps.check_fork_tag.outputs.exists }}"

      - name: Merge upstream tag if not present
        if: steps.check_fork_tag.outputs.exists == 'false'
        id: merge
        run: |
          git checkout master
          git merge ${{ env.LATEST_TAG }} --no-ff --allow-unrelated-histories
        continue-on-error: true

      - name: Check merge result
        if: steps.check_fork_tag.outputs.exists == 'false'
        run: |
          if [ "${{ steps.merge.outcome }}" = "failure" ]; then
            echo "MERGE_FAILED=true" >> $GITHUB_ENV
          else
            echo "MERGE_FAILED=false" >> $GITHUB_ENV
          fi

      - name: Push changes and tag if merge succeeded
        if: steps.check_fork_tag.outputs.exists == 'false' && env.MERGE_FAILED == 'false'
        run: |
          git push origin master
          git tag ${{ env.LATEST_TAG }}
          git push origin ${{ env.LATEST_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue if merge failed
        if: steps.check_fork_tag.outputs.exists == 'false' && env.MERGE_FAILED == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Sync failed: Merge conflict for upstream tag ${{ env.LATEST_TAG }}",
              body: "Automatic sync with upstream tag `${{ env.LATEST_TAG }}` failed due to merge conflicts. Please resolve manually.",
              assignees: ["your-github
